### PR TITLE
Adding Eloquent's namespace in Tree

### PR DESCRIPTION
**Pull request by Alustau**

### CODE REVIEW

**Comment by AdrianSkierniewski** [comment]
First of all, Thank you for publishing this PR.
As far as I remember, I used this alias to still have the ability to override different class than base Eloquent model (for example add your Eloquent class to global \Eloquent alias and then Tree will extend it instead of default Laravel model).
Right now I don't this that this is a good solution, I'd rather create trait to solve this issue, but this library was created some time ago.

Is it causing some problems with your implementation? We can merge it but I'd like to make sure that this is something that we realy need.

**Comment by Alustau** [comment]
Hello, man!

First all, congratulations for your library. It's very helpful for me.
I published it, because is crashing my app when it being loaded. I don't like much this solution, because I don't know much about it! I need search about it, but I'll use this solution. Open a issue =D

**Comment by AdrianSkierniewski** [comment]
I decided to merge this one

**Comment by Alustau** [comment]
@AdrianSkierniewski =D

**Pull request merged**
